var languege = {

	defaults : {
		key: "defaults",
		name: "default",
		title: "Frequent Access",
		setting: "Setting",
		saveAll: "Save All",
		openAll: "Open All URL",
		saveTabs: "Save Tab's URL",
		reset: "Reset",
		add: "Add",
		save: "Save",
		openUrl: "Open URL",

		phSiteTitle: "Site Title",
		phURL: "http://",
		imgPath: "img/plus.png",
	},

	japanese: {
		key: "japanese",
		name: "日本語",
		title: "よく使うURLまとめ",
		setting: "設定",
		saveAll: "一括保存",
		openAll: "全てのURLを開く",
		saveTabs: "現在開いているタブのURLを保存する",
		reset: "全削除",
		add: "追加",
		save: "保存",
		openUrl: "URLを開く",
		phSiteTitle: "サイト名",
		phURL: "http://",
		imgPath: "img/plus.png",
	},

	cyu2: {
		key: "cyu2",
		name: "中二病",
		title: "封印されし魔法書",
		setting: "魔法書",
		saveAll: "聖遺物創造",
		openAll: "閉ざされし魔界の扉を開かん",
		saveTabs: "魔瘴収束",
		reset: "忘却の闇",
		add: "出現せよ",
		save: "刻印",
		openUrl: "召喚",
		phSiteTitle: "賜りし二つ名",
		phURL: "http://",
		imgPath: "img/plus.png",
	},

	cogo: {
		key: "cogo",
		name: "古語",
		title: "かしこし使われしゆーあーるえるを保管いたす",
		setting: "からくり",
		saveAll: "すべてを仕舞い候",
		openAll: "すべてを開き候",
		saveTabs: "集めたりて仕舞いや",
		reset: "けさんとや",
		add: "＊＊＊",
		save: "くはふ",
		openUrl: "ひらきて",
		phSiteTitle: "御名",
		phURL: "えいちてぃーてぃーぴー",
		imgPath: "img/plus.png",
	},

}

