var language = {

	defaults : {
		key: "defaults",
		name: "default",
		title: "Frequent Access",
		setting: "Setting",
		saveAll: "Save All",
		openAll: "Open All URL",
		saveTabs: "Save Opened Tab's URL",
		reset: "Reset",
		add: "Add",
		save: "Save",
		openUrl: "Open URL",
		useParam: "Use Login Param",

		phSiteTitle: "Site Title",
		phURL: "http://",
		phName: "name",
		phValue: "value",
		button: "normal",

		msgClearConfirm: "Are you sure you want to delete the URL data of all? \nYou can not undo this operation.",
		msgSaveTabData: "Are you sure you want to save the URL of the data tab of all of the currently open?",
		msgDeleteConfirm: "Are you sure you want to delete?",
		msgDeleted: "Has been deleted.",
		msgSaved: "Saved.",
		msgIncorrectLogin: "Login data has not been entered correctly.",
		msgIncorrectUrl: "Is not in the correct format of the URL.",
		msgIncorrectData: "Data has not been entered correctly.",
	},

	japanese: {
		key: "japanese",
		name: "日本語",
		title: "URLまとめてみました",
		setting: "設定",
		saveAll: "一括保存",
		openAll: "全てのURLを開く",
		saveTabs: "現在のタブのURLを保存する",
		reset: "全削除",
		add: "追加",
		save: "保存",
		openUrl: "URLを開く",
		useParam: "ログイン機能を使う",

		phSiteTitle: "サイト名",
		phURL: "http://",
		phName: "名前",
		phValue: "値",
		button: "normal",

		msgClearConfirm: "全てのURLデータを削除しますか？\nこの操作は元に戻せません",
		msgSaveTabData: "現在開いているタブのURLデータを保存しますか？",
		msgDeleteConfirm: "削除しますか？",
		msgDeleted: "削除しました",
		msgSaved: "保存しました",
		msgIncorrectLogin: "ログインデータが正しく入力されていません",
		msgIncorrectUrl: "URLの形式が正しくありません",
		msgIncorrectData: "情報が正しく入力されていません",
	},

	cyu2: {
		key: "cyu2",
		name: "中二病",
		title: "封印されし魔法書",
		setting: "魔法書",
		saveAll: "聖遺物創造",
		openAll: "閉ざされし魔界の扉を開かん",
		saveTabs: "魔瘴吸収",
		reset: "忘却の闇",
		add: "出現せよ",
		save: "刻印",
		openUrl: "召喚",
		useParam: "古代呪文の詠唱",

		phSiteTitle: "賜りし二つ名",
		phURL: "http://",
		phName: "名",
		phValue: "ステータス",
		button: "magic",

		msgClearConfirm: "汝、蓄積せし魔術を忘却へと誘うか！",
		msgSaveTabData: "漂いし魔瘴を吸収し、汝の糧と為すか！",
		msgDeleteConfirm: "汝、闇の彼方へ追放するか！",
		msgDeleted: "追放完了",
		msgSaved: "刻印完了",
		msgIncorrectLogin: "古代呪文書をもう一度見直してみたまえ",
		msgIncorrectUrl: "召喚呪文が間違っているだと・・・！",
		msgIncorrectData: "私としたことが・・・どうやら刻印に失敗したようだ。",
	},

	cogo: {
		key: "cogo",
		name: "江戸",
		title: "いと使われし頁を保管ゐたす",
		setting: "設け定める",
		saveAll: "すべてを記し候",
		openAll: "すべてを開き候",
		saveTabs: "よろずに集めたりて記しけり",
		reset: "よろずを消さんとや",
		add: "加ふ",
		save: "記しや",
		openUrl: "開きや",
		useParam: "通行手形を渡したし",

		phSiteTitle: "御名",
		phURL: "ゑいちてーてーぴー",
		phName: "名前",
		phValue: "値",
		button: "kanji",

		msgClearConfirm: "元に戻せざるが、貯めし「ゆーあーるえる」を消すや？",
		msgSaveTabData: "よろずの知識を集めたりて、手記と致すや？",
		msgDeleteConfirm: "消すや？",
		msgDeleted: "消しき。",
		msgSaved: "記したり",
		msgIncorrectLogin: "この通行手形は正しくなし",
		msgIncorrectUrl: "ゆーあーるえるに僻事ありき",
		msgIncorrectData: "記し情報、欠けたり",
	},
}

